name = "cf-ai-footprint"
main = "src/index.ts"
compatibility_date = "2024-12-30"

[ai]
binding = "AI"

[[d1_databases]]
binding = "footprint_db"
database_name = "footprint-db"
database_id = "79738138-2a85-493d-aac6-a4ceef24adcb"

[triggers]
crons = ["0 * * * *"]
